### ISSUE TITLE
How to proceed to add nginx as an ingress claim provider

### ISSUE THREAD

**Issue by zwindler** [yahoo/k8s-ingress-claim#2]
Hi,

What would be needed to add nginx as a new ingress claim provider? I've looked at the code but I have no idea where to start

**Comment by prabushyam** [comment]
You can have an nginx provider that implement [these interface](https://github.com/yahoo/k8s-ingress-claim/blob/master/pkg/provider/types.go#L16-L28) methods. You can take a look at the [istio](https://github.com/yahoo/k8s-ingress-claim/blob/master/pkg/provider/istio.go) example. 

What's your use case with nginx?

**Comment by zwindler** [comment]
Thanks

We have nginx as our Ingress controller and we want to prevent developpers to claim the same hostname in different ingresses (just like it was presented in 101 ways to break K8s at Kubecon Europe)

**Comment by zwindler** [comment]
I'm working on a 1.10 Kubernetes cluster, which uses **admissionregistration.k8s.io/v1beta1** (not **admissionregistration.k8s.io/v1alpha1** like here)

In beta1, there doesn't seem to be a kind: **ExternalAdmissionHookConfiguration** anymore (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#webhook-v1beta1-admissionregistration), but **validatingWebhookConfiguration** looks really similar.

example/admissionregistration.yaml looks like this
```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: k8s-ingress-claim
webhooks:
  - name: k8s-ingress-claim.yahoo.com
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - ingresses
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: default
        name: k8s-ingress-claim
      caBundle: MYOWNCABUNDLE"
```

I think this is OK but I can't be sure yet : I'm not familiar with Go nor with manipulating Kubernetes in the Go code like you do in the Istio example, and I'm having trouble to make it work.

If I understand correctly, Kubernetes should be passing Ingress information to the k8s-ingress-claim Go web service, when a new Ingress is created. Correct?

But I have no idea how to play with this data or debug what my web service is doing. In the logs, I'm only getting Serving GET /status.html from the livenessProbe. 
Shouldn't I also get logs from Ingresses being created ? What bothers me is that I don't...
